!define isprimary #43ADB0
!define issecondary #075D5F
!define background #C9E4E5

hide footbox

skinparam {
    shadowing false
    backgroundColor white
    defaultFontName Arial
    defaultFontColor issecondary
    ArrowColor issecondary
    ActorBorderColor isprimary
    ActorBackgroundColor background
    titleBorderThickness 2
    titleBorderColor issecondary
    stereotypeCBackgroundColor background
    stereotypeCBorderColor issecondary

    sequence {
        LifeLineBorderColor issecondary

        ParticipantBorderColor isprimary
        ParticipantBackgroundColor background

        GroupBorderColor isprimary
        GroupBackgroundColor background
        GroupHeaderFontColor white
    }

    usecase {
        BackgroundColor background
        BorderColor isprimary
    }

    activity {
        StartColor issecondary

        BorderColor isprimary
        BackgroundColor background

        DiamondBorderColor isprimary
        DiamondBackgroundColor background

        EndColor issecondary
        EndBorderColor issecondary
    }

    class {
        BackgroundColor background
        BorderColor isprimary        
    }

    package {
        BackgroundColor white
        BorderColor isprimary
    }

    cloud {
        BackgroundColor background
        BorderColor isprimary
    }
    
    database {
        BackgroundColor background
        BorderColor isprimary
    }

    node {
        BackgroundColor #D9F7F8
        BorderColor isprimary
    }

    note {
        BackgroundColor #F3F3F3
        BorderColor issecondary
    }

    component {
        BackgroundColor background
        BorderColor isprimary
    }

    interface {
        BackgroundColor background
        BorderColor isprimary
    }

    state {
        BackgroundColor background
        BorderColor isprimary
        StartColor issecondary
        EndColor issecondary
    }

    queue {
        BackgroundColor background
        BorderColor isprimary
    }
}
