@startuml
!includeurl ../design.puml

Title Activity diagram

start
:Action 1;

:Action 2;

:Action 3;

if (Statement) then (yes)
    :Yes Action;
else (no)
    :No Action;
endif

:Action 4;

stop
@enduml