@startuml
!includeurl ../design.puml

Title Sequence diagram
actor Actor1 as a1 
participant Participant1 as p1
participant Participant2 as p2 

a1 -> p1: Request 1
a1 <-- p1: Return message for request 1
a1 -> p2: Request 2
p2 -> p2: Validate request 2

@enduml